import { EmailProvider, ContactEnquiryEmailData, JobApplicationEmailData } from './email.types';
import { MockEmailProvider } from './providers/mock.provider';
import { SmtpEmailProvider } from './providers/smtp.provider';

class EmailService {
  private provider: EmailProvider;
  private defaultFrom: string;
  private contactTo: string;
  private careersTo: string;

  constructor() {
    this.defaultFrom = process.env.EMAIL_FROM || 'no-reply@unb.co.za';
    this.contactTo = process.env.EMAIL_CONTACT_TO || 'info@unb.co.za';
    this.careersTo = process.env.EMAIL_CAREERS_TO || 'careers@unb.co.za';

    const providerType = process.env.EMAIL_PROVIDER || 'mock';

    if (providerType === 'smtp') {
      this.provider = new SmtpEmailProvider({
        host: process.env.SMTP_HOST || 'localhost',
        port: parseInt(process.env.SMTP_PORT || '587', 10),
        secure: process.env.SMTP_SECURE === 'true',
        user: process.env.SMTP_USER,
        password: process.env.SMTP_PASSWORD,
        from: this.defaultFrom,
      });
    } else {
      this.provider = new MockEmailProvider();
    }
  }

  public getProviderName(): string {
    return this.provider.name;
  }

  /**
   * Send notification for a new Contact Enquiry
   */
  public async sendContactNotification(
    enquiry: ContactEnquiryEmailData
  ): Promise<{ success: boolean; error?: string }> {
    const formattedDate = new Date(enquiry.createdAt).toUTCString();
    const subject = `[UNB Website Enquiry] ${enquiry.enquiryType} - from ${enquiry.name}`;

    const text = `New Contact Enquiry Received:
---------------------------------------------
Name: ${enquiry.name}
Email: ${enquiry.email}
Phone: ${enquiry.phone || 'Not provided'}
Enquiry Type: ${enquiry.enquiryType}
Received At: ${formattedDate}

Message:
${enquiry.message}
---------------------------------------------
View and manage this enquiry in the UNB Admin CMS.`;

    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #1E2229; margin: 0; padding: 20px; background-color: #F7F6F2; }
    .card { max-width: 600px; margin: 0 auto; background: #ffffff; border: 1px solid #E5E7EB; border-radius: 4px; overflow: hidden; }
    .header { background: #132B5B; color: #ffffff; padding: 24px; }
    .header h2 { margin: 0 0 6px 0; font-size: 20px; font-weight: 800; letter-spacing: -0.5px; }
    .header p { margin: 0; font-size: 12px; color: #D99B26; font-weight: bold; text-transform: uppercase; letter-spacing: 1px; }
    .body { padding: 24px; font-size: 14px; line-height: 1.6; }
    .field { margin-bottom: 12px; }
    .field strong { color: #132B5B; display: inline-block; width: 130px; font-size: 12px; text-transform: uppercase; }
    .message-box { background: #F9FAFB; border-left: 3px solid #D99B26; padding: 16px; margin-top: 16px; border-radius: 2px; font-style: italic; color: #374151; white-space: pre-wrap; }
    .footer { padding: 16px 24px; background: #F3F4F6; font-size: 11px; color: #6B7280; text-align: center; border-top: 1px solid #E5E7EB; }
  </style>
</head>
<body>
  <div class="card">
    <div class="header">
      <p>United National Breweries</p>
      <h2>New Contact Enquiry</h2>
    </div>
    <div class="body">
      <div class="field"><strong>Sender Name:</strong> ${escapeHtml(enquiry.name)}</div>
      <div class="field"><strong>Email Address:</strong> <a href="mailto:${escapeHtml(enquiry.email)}">${escapeHtml(enquiry.email)}</a></div>
      <div class="field"><strong>Phone Number:</strong> ${escapeHtml(enquiry.phone || 'Not provided')}</div>
      <div class="field"><strong>Enquiry Type:</strong> ${escapeHtml(enquiry.enquiryType)}</div>
      <div class="field"><strong>Received Date:</strong> ${formattedDate}</div>
      <div class="message-box">${escapeHtml(enquiry.message)}</div>
    </div>
    <div class="footer">
      This notification was automatically generated by the UNB Web Application portal.
    </div>
  </div>
</body>
</html>`;

    try {
      const result = await this.provider.sendEmail({
        to: this.contactTo,
        subject,
        text,
        html,
      });

      if (!result.success) {
        console.error(`[EMAIL OBSERVABILITY] Contact enquiry email failed for ID ${enquiry.id}: ${result.error}`);
      }
      return result;
    } catch (err) {
      const errMsg = (err as Error).message || 'Email dispatch failed';
      console.error(`[EMAIL OBSERVABILITY] Uncaught error sending contact enquiry email for ID ${enquiry.id}: ${errMsg}`);
      return { success: false, error: errMsg };
    }
  }

  /**
   * Send notification for a new Job Application
   */
  public async sendApplicationNotification(
    application: JobApplicationEmailData
  ): Promise<{ success: boolean; error?: string }> {
    const formattedDate = new Date(application.createdAt).toUTCString();
    const subject = `[UNB Careers Application] ${application.jobTitle} - ${application.name}`;

    const text = `New Candidate Job Application:
---------------------------------------------
Applied Role: ${application.jobTitle}
Candidate Name: ${application.name}
Email: ${application.email}
Phone: ${application.phone}
CV Attached: ${application.hasCv ? `Yes (${application.cvFileName || 'Uploaded'})` : 'No'}
Submitted At: ${formattedDate}

Cover Message / Note:
${application.coverMessage || 'None provided'}
---------------------------------------------
Access and review candidate details & CV securely in the UNB Admin CMS.`;

    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #1E2229; margin: 0; padding: 20px; background-color: #F7F6F2; }
    .card { max-width: 600px; margin: 0 auto; background: #ffffff; border: 1px solid #E5E7EB; border-radius: 4px; overflow: hidden; }
    .header { background: #132B5B; color: #ffffff; padding: 24px; }
    .header h2 { margin: 0 0 6px 0; font-size: 20px; font-weight: 800; letter-spacing: -0.5px; }
    .header p { margin: 0; font-size: 12px; color: #D99B26; font-weight: bold; text-transform: uppercase; letter-spacing: 1px; }
    .body { padding: 24px; font-size: 14px; line-height: 1.6; }
    .field { margin-bottom: 12px; }
    .field strong { color: #132B5B; display: inline-block; width: 140px; font-size: 12px; text-transform: uppercase; }
    .badge { display: inline-block; padding: 2px 8px; font-size: 11px; font-weight: bold; background: #E0E7FF; color: #3730A3; border-radius: 2px; }
    .message-box { background: #F9FAFB; border-left: 3px solid #132B5B; padding: 16px; margin-top: 16px; border-radius: 2px; font-style: italic; color: #374151; white-space: pre-wrap; }
    .footer { padding: 16px 24px; background: #F3F4F6; font-size: 11px; color: #6B7280; text-align: center; border-top: 1px solid #E5E7EB; }
  </style>
</head>
<body>
  <div class="card">
    <div class="header">
      <p>United National Breweries — Recruitment</p>
      <h2>New Job Application</h2>
    </div>
    <div class="body">
      <div class="field"><strong>Position:</strong> <span class="badge">${escapeHtml(application.jobTitle)}</span></div>
      <div class="field"><strong>Candidate Name:</strong> ${escapeHtml(application.name)}</div>
      <div class="field"><strong>Email Address:</strong> <a href="mailto:${escapeHtml(application.email)}">${escapeHtml(application.email)}</a></div>
      <div class="field"><strong>Phone Number:</strong> ${escapeHtml(application.phone || 'Not provided')}</div>
      <div class="field"><strong>CV Attachment:</strong> ${application.hasCv ? escapeHtml(application.cvFileName || 'Uploaded (Secure Private Storage)') : 'No CV Attached'}</div>
      <div class="field"><strong>Applied Date:</strong> ${formattedDate}</div>
      <div class="message-box">${escapeHtml(application.coverMessage || 'No cover note provided.')}</div>
    </div>
    <div class="footer">
      Review application and securely download candidate CV in the UNB Admin CMS.
    </div>
  </div>
</body>
</html>`;

    try {
      const result = await this.provider.sendEmail({
        to: this.careersTo,
        subject,
        text,
        html,
      });

      if (!result.success) {
        console.error(`[EMAIL OBSERVABILITY] Job application email failed for ID ${application.id}: ${result.error}`);
      }
      return result;
    } catch (err) {
      const errMsg = (err as Error).message || 'Email dispatch failed';
      console.error(`[EMAIL OBSERVABILITY] Uncaught error sending job application email for ID ${application.id}: ${errMsg}`);
      return { success: false, error: errMsg };
    }
  }
}

function escapeHtml(str?: string | null): string {
  if (!str) return '';
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

export const emailService = new EmailService();
